import { highlightPoint, pointTargets, quadrant } from '../builders';
import type { Section } from '../types';

export const hittingSection: Section = {
  id: 'hitting',
  title: 'Hitting',
  subtitle: 'Blots, the bar and coming back in',
  icon: 'target',
  color: '#FF8A3D',
  goal: 'Hit blots and re-enter from the bar.',
  lessons: [
    {
      id: 'hitting-1',
      sectionId: 'hitting',
      title: 'Blots',
      description: 'Lonely checkers are in danger.',
      icon: 'alert-circle-outline',
      difficulty: 2,
      skill: 'hitting',
      purpose: {
        outcome: 'Spot the blots on both sides of the board.',
        requires: ['rules'],
        shows: 'what',
        decision: 'tap-theirs',
        inGame: 'Before every move, look for blots: theirs to hit, yours to protect.',
      },
      passingScore: 0,
      xp: 15,
      objectives: [
        { id: 'blot', text: 'Spot a blot' },
        { id: 'safe', text: 'Tell safe checkers from exposed ones' },
      ],
      steps: [
        {
          id: 'what',
          kind: 'explain',
          title: 'Blots',
          text: 'A checker **alone** on a point is a **blot**. Blots can be hit.',
          board: {
            position: { player1: { 13: 4, 9: 1, 6: 4 }, player2: { 19: 4, 17: 3 } },
            highlights: [highlightPoint(9, 'danger', 'Blot')],
          },
        },
        {
          id: 'safe',
          kind: 'explain',
          title: 'Safe points',
          text: 'Two or more checkers together are **safe**. Nobody can hit them.',
          board: {
            position: { player1: { 13: 4, 9: 1, 6: 4 }, player2: { 19: 4, 17: 3 } },
            highlights: [highlightPoint(13, 'success', 'Safe'), highlightPoint(6, 'success', 'Safe')],
          },
        },
        {
          id: 'tap-own',
          kind: 'tap',
          prompt: 'Tap one of **your** blots.',
          board: { position: { player1: { 13: 3, 9: 1, 6: 3, 4: 1 }, player2: { 19: 3, 17: 1, 12: 2 } } },
          answers: pointTargets(9, 4),
          correct: 'Yes, that checker is all alone: a blot.',
          wrong: 'That point has {count} checkers. Look for one of your checkers standing alone.',
          wrongCases: [{ targets: pointTargets(17), text: 'That one is a blot, but it’s your opponent’s. Find one of yours.' }],
        },
        {
          id: 'tap-theirs',
          kind: 'tap',
          prompt: 'Now tap your **opponent’s** blot.',
          board: { position: { player1: { 13: 3, 9: 1, 6: 3, 4: 1 }, player2: { 19: 3, 17: 1, 12: 2 } } },
          answers: pointTargets(17),
          correct: 'Right: a single dark checker on the 17-point.',
          wrong: 'Look for a dark checker standing alone.',
        },
        {
          id: 'which-safe',
          kind: 'choice',
          prompt: 'Which of your checkers can **not** be hit?',
          board: {
            position: { player1: { 11: 1, 8: 2, 5: 1 }, player2: { 19: 3, 17: 2 } },
          },
          options: [
            { id: '11', text: 'The one on the 11-point', explanation: 'It’s alone, so it’s a blot and can be hit.' },
            {
              id: '8',
              text: 'The ones on the 8-point',
              correct: true,
              explanation: 'Correct. Two checkers together make a safe point.',
            },
            { id: '5', text: 'The one on the 5-point', explanation: 'A single checker is a blot, even in your home board.' },
          ],
        },
      ],
    },
    {
      id: 'hitting-2',
      sectionId: 'hitting',
      title: 'Hitting',
      description: 'Send your opponent back to the start.',
      icon: 'sword',
      difficulty: 2,
      skill: 'hitting',
      purpose: {
        outcome: 'Hit a blot with one die or with both together.',
        requires: ['hitting'],
        shows: 'demo',
        decision: 'hit-two-dice',
        inGame: 'With every roll, check whether a number or the total lands on one of their blots.',
      },
      passingScore: 0,
      xp: 20,
      objectives: [
        { id: 'hit', text: 'Hit a blot' },
        { id: 'why', text: 'Know why hitting helps' },
      ],
      steps: [
        {
          id: 'demo',
          kind: 'demo',
          title: 'Hit!',
          text: 'Land on an opponent’s blot to **hit** it. It goes to the **bar**.',
          board: { position: { player1: { 13: 2 }, player2: { 10: 1, 19: 3 } } },
          moves: [{ from: 13, to: 10, caption: 'Hit! The dark checker goes to the bar.' }],
        },
        {
          id: 'start-over',
          kind: 'explain',
          title: 'Back to the start',
          text: 'A hit checker must re-enter at the **very start** of its journey. That costs your opponent a lot of ground.',
          board: {
            position: { player1: { 13: 1, 10: 1 }, player2: { 19: 3 }, bar: { player2: 1 } },
            highlights: [{ region: { kind: 'bar' }, tone: 'gold' }, quadrant('player1-home', 'info', 'Re-enters here')],
          },
        },
        {
          id: 'hit-one',
          kind: 'move',
          prompt: 'You rolled **3-2**. Hit the blot!',
          board: { position: { player1: { 13: 2, 8: 2 }, player2: { 10: 1, 19: 3, 17: 2 } }, dice: [3, 2] },
          goal: { type: 'hit', point: 10 },
          solution: '13/10* 13/11',
          correct: 'Hit! Your opponent has to start that checker all over again.',
          wrong: 'The blot is on the 10-point. Which checker is exactly 3 away?',
        },
        {
          id: 'hit-two-dice',
          kind: 'move',
          prompt: 'You rolled **4-2**. Use **both** numbers to reach and hit the blot.',
          board: { position: { player1: { 13: 2 }, player2: { 7: 1, 19: 3, 17: 2 } }, dice: [4, 2] },
          goal: { type: 'hit', point: 7 },
          solution: '13/7*',
          correct: 'Great. 4 + 2 = 6 took you straight onto the blot.',
          wrong: 'The blot is 6 away from the 13-point: use 4 and 2 on the same checker.',
        },
        {
          id: 'why',
          kind: 'choice',
          prompt: 'Why is hitting usually good for you?',
          options: [
            {
              id: 'ground',
              text: 'Your opponent loses ground and must re-enter',
              correct: true,
              explanation: 'Exactly. The hit checker goes back to the start, setting your opponent back in the race.',
            },
            {
              id: 'capture',
              text: 'The checker is removed from the game',
              explanation: 'It isn’t removed: it goes to the bar and must come back in from the start.',
            },
            {
              id: 'bonus',
              text: 'You get an extra turn',
              explanation: 'No extra turn. The gain is that your opponent loses ground.',
            },
          ],
        },
      ],
    },
    {
      id: 'hitting-3',
      sectionId: 'hitting',
      title: 'Entering from the Bar',
      description: 'Getting back into the game after a hit.',
      icon: 'login',
      difficulty: 2,
      skill: 'rules',
      purpose: {
        outcome: 'Enter from the bar first, on a point that’s open.',
        requires: ['hitting'],
        shows: 'where',
        decision: 'tap-entry',
        inGame: 'After you’re hit, find the number that lands on an open point in their home board.',
      },
      passingScore: 0.5,
      xp: 20,
      objectives: [
        { id: 'first', text: 'Enter before moving anything else' },
        { id: 'where', text: 'Know where each number enters' },
        { id: 'blocked', text: 'Handle blocked entry points' },
      ],
      steps: [
        {
          id: 'must-enter',
          kind: 'explain',
          title: 'On the bar',
          text: 'When you’re hit, your checker waits on the **bar**. It must come back in **before** anything else moves.',
          board: {
            position: { player1: { 13: 4, 8: 3, 6: 4 }, player2: { 19: 4, 12: 3 }, bar: { player1: 1 } },
            highlights: [{ region: { kind: 'bar' }, tone: 'gold' }],
          },
        },
        {
          id: 'where',
          kind: 'explain',
          title: 'Where you enter',
          text: 'You enter in your **opponent’s home board**: a 1 lands on the 24-point, a 6 on the 19-point.',
          board: {
            position: { player1: { 13: 4, 8: 3, 6: 4 }, bar: { player1: 1 } },
            highlights: [highlightPoint(24, 'gold', '1'), highlightPoint(19, 'gold', '6')],
          },
        },
        {
          id: 'enter-3',
          kind: 'move',
          prompt: 'Enter your checker with the **3**.',
          board: {
            position: { player1: { 13: 4, 8: 3, 6: 4 }, player2: { 19: 3, 12: 3 }, bar: { player1: 1 } },
            dice: [3],
          },
          goal: { type: 'enter' },
          solution: 'bar/22',
          correct: 'In! A 3 enters on the 22-point (25 − 3).',
          wrong: 'Tap the checker on the bar, then the highlighted entry point.',
        },
        {
          id: 'enter-then-move',
          kind: 'move',
          prompt: 'You rolled **5-2**. The 5 can’t enter. Enter with the 2, then play the 5.',
          board: {
            position: { player1: { 13: 4, 8: 3, 6: 4 }, player2: { 20: 3, 12: 3 }, bar: { player1: 1 } },
            highlights: [highlightPoint(20, 'danger', 'Blocked')],
            dice: [5, 2],
          },
          goal: { type: 'enter' },
          solution: 'bar/23 13/8',
          correct: 'Exactly. Once you’re back in, the other number is free to move any checker.',
          wrong: 'Enter first with the 2 (on the 23-point), then move any checker 5.',
        },
        {
          id: 'shut-out',
          kind: 'choice',
          prompt: 'You’re on the bar and roll **6-4**. Can you enter?',
          board: {
            position: { player1: { 13: 4, 8: 3, 6: 4 }, player2: { 19: 2, 21: 2, 12: 3 }, bar: { player1: 1 } },
            highlights: [highlightPoint(19, 'danger'), highlightPoint(21, 'danger')],
            dice: [6, 4],
          },
          options: [
            {
              id: 'no',
              text: 'No, both entry points are blocked',
              correct: true,
              explanation: 'Right. A 6 needs the 19-point and a 4 needs the 21-point. Both are blocked, so your turn passes.',
            },
            {
              id: 'yes',
              text: 'Yes, on the 19-point',
              explanation: 'The 19-point is held by two dark checkers, and so is the 21-point. You can’t enter this turn.',
            },
            {
              id: 'other',
              text: 'You can move another checker instead',
              explanation: 'Not while a checker is on the bar: it must enter first. Since it can’t, your turn passes.',
            },
          ],
        },
        {
          id: 'tap-entry',
          kind: 'tap',
          prompt: 'You rolled a **5**. Tap where your checker on the bar enters.',
          board: {
            position: { player1: { 13: 4, 8: 3, 6: 4 }, player2: { 12: 3 }, bar: { player1: 1 } },
            dice: [5],
          },
          answers: pointTargets(20),
          correct: 'Yes: 25 − 5 = 20. A 5 enters on the 20-point.',
          wrong: 'A 1 enters on the 24-point and each number counts one point further. Try 25 − 5.',
        },
      ],
    },
    {
      id: 'hitting-4',
      sectionId: 'hitting',
      title: 'How Risky Is a Blot?',
      description: 'Count the rolls that hit before you leave a blot.',
      icon: 'crosshairs-question',
      difficulty: 2,
      skill: 'shots',
      purpose: {
        outcome: 'Tell a blot in direct range from one only a combination can hit.',
        requires: ['hitting'],
        shows: 'direct',
        decision: 'safer-spot',
        inGame: 'Before you leave a blot, count how far it is from their checkers: 6 or less is a direct shot.',
      },
      passingScore: 0.5,
      xp: 20,
      objectives: [
        { id: 'behind', text: 'Know that a blot behind every enemy checker is safe' },
        { id: 'direct', text: 'Tell direct shots from indirect ones' },
        { id: 'count', text: 'Know roughly how often a close blot is hit' },
      ],
      steps: [
        {
          id: 'behind',
          kind: 'choice',
          prompt: 'Can any dark checker hit your blot on the **4-point**?',
          board: {
            position: { player1: { 13: 3, 8: 3, 6: 4, 5: 2, 4: 1, 3: 2 }, player2: { 12: 3, 17: 3, 19: 4, 20: 3, 21: 2 } },
            highlights: [highlightPoint(4, 'danger', 'Blot')],
          },
          options: [
            {
              id: 'no',
              text: 'No: every dark checker has already passed it',
              correct: true,
              explanation: 'Right. Checkers only move forward, and all of theirs are past your 4-point. A blot behind them is safe.',
            },
            {
              id: 'yes',
              text: 'Yes: the checkers on your 12-point can reach it',
              explanation: 'They move the other way, toward your 24-point. A checker can only hit blots in front of it.',
            },
          ],
        },
        {
          id: 'direct',
          kind: 'explain',
          title: 'Direct shots',
          text: 'A blot **6 pips or fewer** in front of an enemy checker is in **direct** range: one number hits it.',
          board: {
            position: { player1: { 24: 2, 13: 5, 8: 3, 6: 4, 5: 1 }, player2: { 1: 2, 12: 5, 17: 3, 19: 5 } },
            highlights: [highlightPoint(5, 'danger', '4 away'), highlightPoint(1, 'info')],
          },
        },
        {
          id: 'tap-direct',
          kind: 'tap',
          prompt: 'Two blots. Which one is in **direct** range of their back checkers? Tap it.',
          board: { position: { player1: { 24: 2, 13: 4, 10: 1, 8: 2, 6: 5, 5: 1 }, player2: { 1: 2, 12: 5, 17: 3, 19: 5 } } },
          answers: pointTargets(5),
          correct: 'Yes. It’s 4 pips from their checkers on your 1-point: any 4 hits it.',
          wrong: 'That point isn’t a blot in their range. Find your lone checker closest in front of their back checkers.',
          wrongCases: [
            {
              targets: pointTargets(10),
              text: 'That one is 9 away. No single number reaches it, only combinations like 6-3 or 5-4: an indirect shot.',
            },
          ],
        },
        {
          id: 'count-11',
          kind: 'choice',
          prompt: 'How many of the 36 possible rolls contain at least one **4**?',
          options: [
            { id: '6', text: '6', explanation: 'That counts 4-1 to 4-6 only. The 4 can be on either die: 11 rolls, counting 4-4 once.' },
            {
              id: '11',
              text: '11',
              correct: true,
              explanation: 'Right. Any one number shows up in 11 of the 36 rolls: almost 1 time in 3.',
            },
            { id: '12', text: '12', explanation: 'Close! 6 rolls with the 4 on each die, but 4-4 is only one roll: 11.' },
          ],
        },
        {
          id: 'combos',
          kind: 'explain',
          title: 'Combinations',
          text: 'With a blot 4 away, **3-1**, **2-2** and **1-1** hit too: **15 rolls** in all, nearly half.',
          board: {
            position: { player1: { 24: 2, 13: 5, 8: 3, 6: 4, 5: 1 }, player2: { 1: 2, 12: 5, 17: 3, 19: 5 } },
            highlights: [highlightPoint(5, 'danger', '15 rolls')],
          },
          tip: 'From 7 pips away, only combinations can hit: usually 6 rolls or fewer.',
        },
        {
          id: 'safer-spot',
          kind: 'choice',
          prompt: 'You must leave a blot on your 10-point or your 4-point. Their back checkers are on your 1-point. Which is safer?',
          board: {
            position: { player1: { 24: 2, 13: 5, 8: 3, 6: 5 }, player2: { 1: 2, 12: 5, 17: 3, 19: 5 } },
            highlights: [highlightPoint(10, 'info', '?'), highlightPoint(4, 'info', '?')],
          },
          options: [
            {
              id: 'ten',
              text: 'On the 10-point, 9 away',
              correct: true,
              explanation: 'Yes. Nine away is an indirect shot: only 6-3, 5-4 and 3-3 reach it, 5 rolls out of 36.',
            },
            {
              id: 'four',
              text: 'On the 4-point, 3 away',
              explanation: 'That’s a direct shot: any 3 hits it, plus 2-1 and 1-1. That’s 14 rolls, almost three times as many.',
            },
          ],
        },
      ],
    },
  ],
};
