import { highlightPoint, pointTargets, quadrant } from '../builders';
import type { Section } from '../types';

export const hittingSection: Section = {
  id: 'hitting',
  title: 'Hitting',
  subtitle: 'Blots, the bar and coming back in',
  icon: 'target',
  color: '#FF8A3D',
  goal: 'Hit blots and re-enter from the bar.',
  lessons: [
    {
      id: 'hitting-1',
      sectionId: 'hitting',
      title: 'Blots',
      description: 'Lonely checkers are in danger.',
      icon: 'alert-circle-outline',
      difficulty: 2,
      category: 'hitting',
      passingScore: 0,
      xp: 15,
      objectives: [
        { id: 'blot', text: 'Spot a blot' },
        { id: 'safe', text: 'Tell safe checkers from exposed ones' },
      ],
      steps: [
        {
          id: 'what',
          kind: 'explain',
          title: 'Blots',
          text: 'A checker **alone** on a point is a **blot**. Blots can be hit.',
          board: {
            position: { player1: { 13: 4, 9: 1, 6: 4 }, player2: { 19: 4, 17: 3 } },
            highlights: [highlightPoint(9, 'danger', 'Blot')],
          },
        },
        {
          id: 'safe',
          kind: 'explain',
          title: 'Safe points',
          text: 'Two or more checkers together are **safe**. Nobody can hit them.',
          board: {
            position: { player1: { 13: 4, 9: 1, 6: 4 }, player2: { 19: 4, 17: 3 } },
            highlights: [highlightPoint(13, 'success', 'Safe'), highlightPoint(6, 'success', 'Safe')],
          },
        },
        {
          id: 'tap-own',
          kind: 'tap',
          prompt: 'Tap one of **your** blots.',
          board: { position: { player1: { 13: 3, 9: 1, 6: 3, 4: 1 }, player2: { 19: 3, 17: 1, 12: 2 } } },
          answers: pointTargets(9, 4),
          correct: 'Yes, that checker is all alone: a blot.',
          wrong: 'That point has {count} checkers. Look for one of your checkers standing alone.',
          wrongCases: [{ targets: pointTargets(17), text: 'That one is a blot, but it’s your opponent’s. Find one of yours.' }],
        },
        {
          id: 'tap-theirs',
          kind: 'tap',
          prompt: 'Now tap your **opponent’s** blot.',
          board: { position: { player1: { 13: 3, 9: 1, 6: 3, 4: 1 }, player2: { 19: 3, 17: 1, 12: 2 } } },
          answers: pointTargets(17),
          correct: 'Right: a single dark checker on the 17-point.',
          wrong: 'Look for a dark checker standing alone.',
        },
        {
          id: 'which-safe',
          kind: 'choice',
          prompt: 'Which of your checkers can **not** be hit?',
          board: {
            position: { player1: { 11: 1, 8: 2, 5: 1 }, player2: { 19: 3, 17: 2 } },
          },
          options: [
            { id: '11', text: 'The one on the 11-point', explanation: 'It’s alone, so it’s a blot and can be hit.' },
            {
              id: '8',
              text: 'The ones on the 8-point',
              correct: true,
              explanation: 'Correct. Two checkers together make a safe point.',
            },
            { id: '5', text: 'The one on the 5-point', explanation: 'A single checker is a blot, even in your home board.' },
          ],
        },
      ],
    },
    {
      id: 'hitting-2',
      sectionId: 'hitting',
      title: 'Hitting',
      description: 'Send your opponent back to the start.',
      icon: 'sword',
      difficulty: 2,
      category: 'hitting',
      passingScore: 0,
      xp: 20,
      objectives: [
        { id: 'hit', text: 'Hit a blot' },
        { id: 'why', text: 'Know why hitting helps' },
      ],
      steps: [
        {
          id: 'demo',
          kind: 'demo',
          title: 'Hit!',
          text: 'Land on an opponent’s blot to **hit** it. It goes to the **bar**.',
          board: { position: { player1: { 13: 2 }, player2: { 10: 1, 19: 3 } } },
          moves: [{ from: 13, to: 10, caption: 'Hit! The dark checker goes to the bar.' }],
        },
        {
          id: 'start-over',
          kind: 'explain',
          title: 'Back to the start',
          text: 'A hit checker must re-enter at the **very start** of its journey. That costs your opponent a lot of ground.',
          board: {
            position: { player1: { 13: 1, 10: 1 }, player2: { 19: 3 }, bar: { player2: 1 } },
            highlights: [{ region: { kind: 'bar' }, tone: 'gold' }, quadrant('player1-home', 'info', 'Re-enters here')],
          },
        },
        {
          id: 'hit-one',
          kind: 'move',
          prompt: 'You rolled **3-2**. Hit the blot!',
          board: { position: { player1: { 13: 2, 8: 2 }, player2: { 10: 1, 19: 3, 17: 2 } }, dice: [3, 2] },
          goal: { type: 'hit', point: 10 },
          solution: '13/10* 13/11',
          correct: 'Hit! Your opponent has to start that checker all over again.',
          wrong: 'The blot is on the 10-point. Which checker is exactly 3 away?',
        },
        {
          id: 'hit-two-dice',
          kind: 'move',
          prompt: 'You rolled **4-2**. Use **both** numbers to reach and hit the blot.',
          board: { position: { player1: { 13: 2 }, player2: { 7: 1, 19: 3, 17: 2 } }, dice: [4, 2] },
          goal: { type: 'hit', point: 7 },
          solution: '13/7*',
          correct: 'Great. 4 + 2 = 6 took you straight onto the blot.',
          wrong: 'The blot is 6 away from the 13-point: use 4 and 2 on the same checker.',
        },
        {
          id: 'why',
          kind: 'choice',
          prompt: 'Why is hitting usually good for you?',
          options: [
            {
              id: 'ground',
              text: 'Your opponent loses ground and must re-enter',
              correct: true,
              explanation: 'Exactly. The hit checker goes back to the start, setting your opponent back in the race.',
            },
            {
              id: 'capture',
              text: 'The checker is removed from the game',
              explanation: 'It isn’t removed: it goes to the bar and must come back in from the start.',
            },
            {
              id: 'bonus',
              text: 'You get an extra turn',
              explanation: 'No extra turn. The gain is that your opponent loses ground.',
            },
          ],
        },
      ],
    },
    {
      id: 'hitting-3',
      sectionId: 'hitting',
      title: 'Entering from the Bar',
      description: 'Getting back into the game after a hit.',
      icon: 'login',
      difficulty: 2,
      category: 'hitting',
      passingScore: 0.5,
      xp: 20,
      objectives: [
        { id: 'first', text: 'Enter before moving anything else' },
        { id: 'where', text: 'Know where each number enters' },
        { id: 'blocked', text: 'Handle blocked entry points' },
      ],
      steps: [
        {
          id: 'must-enter',
          kind: 'explain',
          title: 'On the bar',
          text: 'When you’re hit, your checker waits on the **bar**. It must come back in **before** anything else moves.',
          board: {
            position: { player1: { 13: 4, 8: 3, 6: 4 }, player2: { 19: 4, 12: 3 }, bar: { player1: 1 } },
            highlights: [{ region: { kind: 'bar' }, tone: 'gold' }],
          },
        },
        {
          id: 'where',
          kind: 'explain',
          title: 'Where you enter',
          text: 'You enter in your **opponent’s home board**: a 1 lands on the 24-point, a 6 on the 19-point.',
          board: {
            position: { player1: { 13: 4, 8: 3, 6: 4 }, bar: { player1: 1 } },
            highlights: [highlightPoint(24, 'gold', '1'), highlightPoint(19, 'gold', '6')],
          },
        },
        {
          id: 'enter-3',
          kind: 'move',
          prompt: 'Enter your checker with the **3**.',
          board: {
            position: { player1: { 13: 4, 8: 3, 6: 4 }, player2: { 19: 3, 12: 3 }, bar: { player1: 1 } },
            dice: [3],
          },
          goal: { type: 'enter' },
          solution: 'bar/22',
          correct: 'In! A 3 enters on the 22-point (25 − 3).',
          wrong: 'Tap the checker on the bar, then the highlighted entry point.',
        },
        {
          id: 'enter-then-move',
          kind: 'move',
          prompt: 'You rolled **5-2**. The 5 can’t enter. Enter with the 2, then play the 5.',
          board: {
            position: { player1: { 13: 4, 8: 3, 6: 4 }, player2: { 20: 3, 12: 3 }, bar: { player1: 1 } },
            highlights: [highlightPoint(20, 'danger', 'Blocked')],
            dice: [5, 2],
          },
          goal: { type: 'enter' },
          solution: 'bar/23 13/8',
          correct: 'Exactly. Once you’re back in, the other number is free to move any checker.',
          wrong: 'Enter first with the 2 (on the 23-point), then move any checker 5.',
        },
        {
          id: 'shut-out',
          kind: 'choice',
          prompt: 'You’re on the bar and roll **6-4**. Can you enter?',
          board: {
            position: { player1: { 13: 4, 8: 3, 6: 4 }, player2: { 19: 2, 21: 2, 12: 3 }, bar: { player1: 1 } },
            highlights: [highlightPoint(19, 'danger'), highlightPoint(21, 'danger')],
            dice: [6, 4],
          },
          options: [
            {
              id: 'no',
              text: 'No, both entry points are blocked',
              correct: true,
              explanation: 'Right. A 6 needs the 19-point and a 4 needs the 21-point. Both are blocked, so your turn passes.',
            },
            {
              id: 'yes',
              text: 'Yes, on the 19-point',
              explanation: 'The 19-point is held by two dark checkers, and so is the 21-point. You can’t enter this turn.',
            },
            {
              id: 'other',
              text: 'You can move another checker instead',
              explanation: 'Not while a checker is on the bar: it must enter first. Since it can’t, your turn passes.',
            },
          ],
        },
        {
          id: 'tap-entry',
          kind: 'tap',
          prompt: 'You rolled a **5**. Tap where your checker on the bar enters.',
          board: {
            position: { player1: { 13: 4, 8: 3, 6: 4 }, player2: { 12: 3 }, bar: { player1: 1 } },
            dice: [5],
          },
          answers: pointTargets(20),
          correct: 'Yes: 25 − 5 = 20. A 5 enters on the 20-point.',
          wrong: 'A 1 enters on the 24-point and each number counts one point further. Try 25 − 5.',
        },
      ],
    },
  ],
};
