import { highlightPoint, highlightPoints, pointTargets, quadrant, range, START } from '../builders';
import type { Section } from '../types';

export const boardSection: Section = {
  id: 'board',
  title: 'Meet the Board',
  subtitle: 'Points, checkers, home and the bar',
  icon: 'checkerboard',
  color: '#62B6FF',
  goal: 'Understand the backgammon board.',
  lessons: [
    {
      id: 'board-1',
      sectionId: 'board',
      title: 'What is Backgammon?',
      description: 'A race with dice, decisions and a little danger.',
      icon: 'flag-checkered',
      difficulty: 1,
      skill: 'board',
      purpose: {
        outcome: 'Tell your checkers from your opponent’s, and say how a game is won.',
        requires: [],
        shows: 'race',
        decision: 'tap-yours',
        inGame: 'Your checkers are the light ones, racing home: bring all 15 in and off first.',
      },
      passingScore: 0,
      xp: 15,
      objectives: [
        { id: 'goal', text: 'Know how you win' },
        { id: 'sides', text: 'Know which checkers are yours' },
      ],
      steps: [
        {
          id: 'race',
          kind: 'explain',
          title: 'A race for two',
          text: 'Backgammon is a **race**. You and your opponent each have **15 checkers**.',
          board: { position: START },
        },
        {
          id: 'tap-yours',
          kind: 'tap',
          prompt: 'You play the **light** checkers. Tap a point with **your** checkers on it.',
          board: { position: START },
          answers: pointTargets(24, 13, 8, 6),
          correct: 'Yes! The light checkers are yours.',
          wrong: 'Those are your opponent’s dark checkers. Yours are the light ones.',
          wrongCases: [
            {
              targets: pointTargets(...range(2, 5), 7, ...range(9, 11), ...range(14, 16), 18, ...range(20, 23)),
              text: 'That point is empty. Look for the light checkers.',
            },
          ],
        },
        {
          id: 'journey',
          kind: 'demo',
          title: 'All the way home',
          text: 'Roll the dice and move. Your checkers travel **all the way around** the board…',
          board: { position: { player1: { 24: 1 } } },
          moves: [
            { from: 24, to: 18, caption: 'Along the top…' },
            { from: 18, to: 13 },
            { from: 13, to: 7, caption: '…around the corner…' },
            { from: 7, to: 3, caption: '…into your home…' },
            { from: 3, to: 'off', caption: '…and off the board!' },
          ],
        },
        {
          id: 'goal-check',
          kind: 'choice',
          prompt: 'Your checkers travel all the way around. What do you think wins the game?',
          options: [
            {
              id: 'capture',
              text: 'Capture all of your opponent’s checkers',
              explanation:
                'Checkers are never captured for good: a hit checker just starts its journey again. You win the race by bearing off.',
            },
            {
              id: 'race',
              text: 'Be first to bear off all 15 of your checkers',
              correct: true,
              explanation: 'Exactly! Backgammon is a race to bring all your checkers home and off the board.',
            },
            {
              id: 'line',
              text: 'Line up five checkers in a row',
              explanation: 'That’s a different game. In backgammon you win by bearing off all 15 checkers first.',
            },
          ],
        },
        {
          id: 'win',
          kind: 'explain',
          title: 'How you win',
          text: 'Be the first to bring all 15 checkers home and **bear them off** the board.',
          board: {
            position: {
              player1: { 1: 2, 3: 1 },
              player2: { 22: 3, 20: 4, 13: 2 },
              off: { player1: 12, player2: 6 },
            },
            highlights: [{ region: { kind: 'off' }, tone: 'gold' }],
          },
          tip: 'Almost there: only three of your checkers are left on the board.',
        },
      ],
    },
    {
      id: 'board-2',
      sectionId: 'board',
      title: 'The 24 Points',
      description: 'Find your way around the board.',
      icon: 'numeric',
      difficulty: 1,
      skill: 'board',
      purpose: {
        outcome: 'Find any point by its number, even with the numbers hidden.',
        requires: ['board'],
        shows: 'numbering',
        decision: 'tap-24',
        inGame: 'When the coach says “make your 5-point”, you’ll know exactly where that is.',
      },
      passingScore: 0,
      xp: 15,
      objectives: [
        { id: 'points', text: 'Know what a point is' },
        { id: 'numbers', text: 'Find any point by its number' },
      ],
      steps: [
        {
          id: 'triangles',
          kind: 'explain',
          title: 'Points',
          text: 'The board has **24 triangles** called **points**. Checkers always sit on points.',
          board: { position: {}, highlights: [highlightPoints(range(1, 24), 'gold')] },
        },
        {
          id: 'numbering',
          kind: 'explain',
          title: 'Your numbers',
          text: 'Points are numbered from **your** side. The **1-point** is bottom right, the **24-point** top right.',
          board: {
            position: {},
            highlights: [highlightPoint(1, 'gold', '1'), highlightPoint(24, 'gold', '24')],
          },
        },
        {
          id: 'tap-6',
          kind: 'tap',
          prompt: 'Tap the **6-point**.',
          board: { position: {} },
          answers: pointTargets(6),
          correct: 'That’s the 6-point. You’ll use it a lot!',
          wrong: 'That’s the {point}-point. Start at the 1-point, bottom right, and count six to the left.',
        },
        {
          id: 'horseshoe',
          kind: 'explain',
          title: 'Like a horseshoe',
          text: 'Count **1 to 12** along the bottom, then **13 to 24** back along the top.',
          board: {
            position: {},
            highlights: [
              highlightPoints(range(1, 12), 'info', '1 → 12'),
              highlightPoints(range(13, 24), 'gold', '13 → 24'),
            ],
          },
        },
        {
          id: 'tap-13',
          kind: 'tap',
          prompt: 'Now tap the **13-point**.',
          board: { position: {} },
          answers: pointTargets(13),
          correct: 'Right, the 13-point sits top left, straight above the 12-point.',
          wrong: 'That’s the {point}-point. The 13-point is top left, just above the 12-point.',
        },
        {
          id: 'tap-24',
          kind: 'tap',
          prompt: 'No numbers this time. Tap the **24-point**.',
          board: { position: {}, showPointNumbers: false },
          answers: pointTargets(24),
          correct: 'Nice! The 24-point is the top-right corner, opposite your 1-point.',
          wrong: 'That’s the {point}-point. The 24-point is the top-right corner.',
          hint: 'It’s directly above the 1-point.',
        },
        {
          id: 'tap-1',
          kind: 'tap',
          prompt: 'And the **1-point**?',
          board: { position: {}, showPointNumbers: false },
          answers: pointTargets(1),
          correct: 'Perfect. Everything starts counting from here.',
          wrong: 'That’s the {point}-point. The 1-point is the bottom-right corner.',
        },
      ],
    },
    {
      id: 'board-3',
      sectionId: 'board',
      title: 'Your Checkers',
      description: 'Count your army and spot your opponent’s.',
      icon: 'circle-multiple',
      difficulty: 1,
      skill: 'board',
      purpose: {
        outcome: 'Count the stacks on both sides of the starting position.',
        requires: ['board'],
        shows: 'fifteen',
        decision: 'tap-opp-three',
        inGame: 'A quick look at the stacks tells you where everyone is before you move.',
      },
      passingScore: 0,
      xp: 15,
      objectives: [
        { id: 'count', text: 'Know you have 15 checkers' },
        { id: 'opponent', text: 'Tell your checkers from your opponent’s' },
      ],
      steps: [
        {
          id: 'fifteen',
          kind: 'explain',
          title: '15 checkers each',
          text: 'You start with **15** light checkers spread over four points.',
          board: { position: START, highlights: [highlightPoints([24, 13, 8, 6], 'gold')] },
        },
        {
          id: 'mirror',
          kind: 'explain',
          title: 'A mirror image',
          text: 'Your opponent’s **15 dark checkers** are set up as a mirror image of yours.',
          board: { position: START, highlights: [highlightPoints([1, 12, 17, 19], 'info')] },
        },
        {
          id: 'tap-three',
          kind: 'tap',
          prompt: 'Tap the point where you have exactly **3** checkers.',
          board: { position: START },
          answers: pointTargets(8),
          correct: 'Yes, three checkers on your 8-point.',
          wrong: 'Count again: that point has {count}. Look for a stack of three light checkers.',
        },
        {
          id: 'tap-opp-three',
          kind: 'tap',
          prompt: 'Now find your opponent’s stack of **3** dark checkers.',
          board: { position: START },
          answers: pointTargets(17),
          correct: 'Right, three dark checkers on your 17-point.',
          wrong: 'That point has {count} checkers on it. Look for three dark ones.',
        },
        {
          id: 'one-owner',
          kind: 'explain',
          title: 'One colour per point',
          text: 'A point can only hold checkers of **one colour** at a time.',
          board: { position: START, highlights: [highlightPoint(13, 'gold'), highlightPoint(12, 'info')] },
        },
        {
          id: 'how-many',
          kind: 'choice',
          prompt: 'How many checkers does each player have?',
          options: [
            { id: '12', text: '12', explanation: 'Not quite. Count the stacks: 2 + 5 + 3 + 5 = 15.' },
            { id: '15', text: '15', correct: true, explanation: 'Correct: 2 + 5 + 3 + 5 = 15 checkers each.' },
            { id: '24', text: '24', explanation: 'There are 24 points, but each player has 15 checkers.' },
          ],
        },
      ],
    },
    {
      id: 'board-4',
      sectionId: 'board',
      title: 'Home Board & the Bar',
      description: 'The four quarters of the board and the bar.',
      icon: 'home-variant',
      difficulty: 1,
      skill: 'board',
      purpose: {
        outcome: 'Find your home board, your opponent’s home board and the bar.',
        requires: ['board'],
        shows: 'quarters',
        decision: 'tap-their-home',
        inGame: 'Your home board is where you build points and bear off; hit checkers wait on the bar.',
      },
      passingScore: 0,
      xp: 15,
      objectives: [
        { id: 'home', text: 'Find your home board' },
        { id: 'bar', text: 'Find the bar' },
      ],
      steps: [
        {
          id: 'quarters',
          kind: 'explain',
          title: 'Four quarters',
          text: 'The board splits into **four quarters** of six points each.',
          board: {
            position: {},
            highlights: [
              quadrant('player1-home', 'gold'),
              quadrant('player1-outer', 'info'),
              quadrant('player2-home', 'danger'),
              quadrant('player2-outer', 'success'),
            ],
          },
        },
        {
          id: 'tap-home',
          kind: 'tap',
          prompt: 'Your checkers all head for the quarter with your **1-point**: your **home board**. Tap any point in it.',
          board: { position: START },
          answers: pointTargets(...range(1, 6)),
          correct: 'Yes: points 1 to 6 are your home board. Every one of your checkers is heading there.',
          wrong: 'That’s the {point}-point. Your home board is the bottom-right quarter: points 1 to 6.',
        },
        {
          id: 'tap-their-home',
          kind: 'tap',
          prompt: 'Your opponent races the other way, to the quarter with your **24-point**. Tap their home board.',
          board: { position: START },
          answers: pointTargets(...range(19, 24)),
          correct: 'Right: points 19 to 24, top right. That’s where their checkers are heading.',
          wrong: 'That’s the {point}-point. Your opponent’s home board is top right: points 19 to 24.',
        },
        {
          id: 'bar',
          kind: 'explain',
          title: 'The bar',
          text: 'The strip down the middle is the **bar**. Checkers that get hit wait there to come back in.',
          board: {
            position: {
              player1: { 24: 2, 13: 5, 8: 3, 6: 4, 5: 1 },
              player2: { 1: 2, 12: 5, 17: 3, 19: 4 },
              bar: { player2: 1 },
            },
            highlights: [{ region: { kind: 'bar' }, tone: 'gold', label: 'The bar' }],
          },
        },
        {
          id: 'tap-bar',
          kind: 'tap',
          prompt: 'Tap the **bar**.',
          board: { position: START },
          answers: [{ kind: 'bar' }],
          correct: 'That’s the bar, right in the middle.',
          wrong: 'The bar is the wooden strip that divides the board down the middle.',
        },
      ],
    },
    {
      id: 'board-5',
      sectionId: 'board',
      title: 'Which Way to Move',
      description: 'Follow the horseshoe from 24 down to 1.',
      icon: 'rotate-left',
      difficulty: 1,
      skill: 'rules',
      purpose: {
        outcome: 'Move a checker the right way and count the spaces.',
        requires: ['board'],
        shows: 'your-way',
        decision: 'count-5',
        inGame: 'Every move you make counts down toward your home board.',
      },
      passingScore: 0,
      xp: 15,
      objectives: [
        { id: 'direction', text: 'Know which way your checkers move' },
        { id: 'count', text: 'Count spaces along the board' },
      ],
      steps: [
        {
          id: 'your-way',
          kind: 'demo',
          title: 'Your direction',
          text: 'You always move **from 24 down to 1**, toward your home board.',
          board: { position: { player1: { 24: 1 } } },
          moves: [
            { from: 24, to: 18, caption: 'Right to left along the top…' },
            { from: 18, to: 13 },
            { from: 13, to: 7, caption: '…then left to right along the bottom.' },
            { from: 7, to: 2 },
          ],
        },
        {
          id: 'their-way',
          kind: 'demo',
          title: 'Their direction',
          text: 'Your opponent moves the **opposite way**: from your 1-point up to your 24-point.',
          board: { position: { player2: { 1: 1 } } },
          moves: [
            { player: 'player2', from: 1, to: 7 },
            { player: 'player2', from: 7, to: 12 },
            { player: 'player2', from: 12, to: 18 },
            { player: 'player2', from: 18, to: 23 },
          ],
        },
        {
          id: 'which-way',
          kind: 'choice',
          prompt: 'Your checker is on the **13-point**. Which way does it move?',
          board: { position: { player1: { 13: 1 } }, highlights: [highlightPoint(13, 'gold')] },
          options: [
            {
              id: 'down',
              text: 'Down to the 12-point side, toward home',
              correct: true,
              explanation: 'Yes. From the 13-point you turn the corner to the 12-point and head for home.',
            },
            {
              id: 'up',
              text: 'Right, toward the 14-point',
              explanation: 'That’s your opponent’s direction. Your checkers always count down toward the 1-point.',
            },
          ],
        },
        {
          id: 'move-3',
          kind: 'move',
          prompt: 'Move your checker **3** spaces. Tap the checker, then tap where it lands.',
          board: { position: { player1: { 13: 1 } }, dice: [3] },
          goal: { type: 'land-on', point: 10 },
          solution: '13/10',
          correct: 'Great! 13 minus 3 lands on the 10-point.',
          wrong: 'Count three points toward home: 12, 11, 10.',
        },
        {
          id: 'count-5',
          kind: 'tap',
          prompt: 'A checker on the **8-point** moves **5**. Tap where it lands.',
          board: { position: { player1: { 8: 1 } }, highlights: [highlightPoint(8, 'gold')], dice: [5] },
          answers: pointTargets(3),
          correct: 'Yes! 7, 6, 5, 4, 3. It lands on the 3-point.',
          wrong: 'Count five points toward home from the 8-point: 7, 6, 5, 4, 3.',
        },
        {
          id: 'move-6',
          kind: 'move',
          prompt: 'Now move this checker **6** spaces.',
          board: { position: { player1: { 24: 1 } }, dice: [6] },
          goal: { type: 'land-on', point: 18 },
          solution: '24/18',
          correct: 'Right! From the 24-point, six spaces gets you to the 18-point.',
          wrong: 'Count six points from the 24-point: 23, 22, 21, 20, 19, 18.',
        },
      ],
    },
    {
      id: 'board-6',
      sectionId: 'board',
      title: 'Setting Up the Board',
      description: 'Place all 15 checkers for a new game.',
      icon: 'grid',
      difficulty: 2,
      skill: 'board',
      purpose: {
        outcome: 'Set up the starting position and name your back checkers and mid-point.',
        requires: ['board'],
        shows: 'intro',
        decision: 'quiz-back',
        inGame: 'Every game starts here: back checkers on 24, mid-point on 13.',
      },
      passingScore: 0.5,
      xp: 20,
      objectives: [
        { id: 'setup', text: 'Set up the starting position' },
        { id: 'names', text: 'Learn the names of your key points' },
      ],
      steps: [
        {
          id: 'intro',
          kind: 'explain',
          title: 'Same start, every game',
          text: 'Every game begins from the same position. Let’s set up your side together.',
          board: { position: {} },
        },
        {
          id: 'place-24',
          kind: 'tap',
          prompt: 'Place **2** checkers on your **24-point**.',
          board: { position: {} },
          answers: pointTargets(24),
          reveal: { player1: { 24: 2 } },
          correct: 'These are your **back checkers**. They have the longest way home.',
          wrong: 'That’s the {point}-point. The 24-point is the top-right corner.',
        },
        {
          id: 'place-13',
          kind: 'tap',
          prompt: 'Place **5** checkers on the **13-point**.',
          board: { position: { player1: { 24: 2 } } },
          answers: pointTargets(13),
          reveal: { player1: { 24: 2, 13: 5 } },
          correct: 'This is your **mid-point**: halfway home.',
          wrong: 'That’s the {point}-point. The 13-point is top left.',
        },
        {
          id: 'place-8',
          kind: 'tap',
          prompt: 'Place **3** checkers on the **8-point**.',
          board: { position: { player1: { 24: 2, 13: 5 } } },
          answers: pointTargets(8),
          reveal: { player1: { 24: 2, 13: 5, 8: 3 } },
          correct: 'Three on the 8-point, just outside your home board.',
          wrong: 'That’s the {point}-point. The 8-point is two to the left of the bar on the bottom.',
        },
        {
          id: 'place-6',
          kind: 'tap',
          prompt: 'Finally, place **5** checkers on the **6-point**.',
          board: { position: { player1: { 24: 2, 13: 5, 8: 3 } } },
          answers: pointTargets(6),
          reveal: { player1: { 24: 2, 13: 5, 8: 3, 6: 5 } },
          correct: 'All 15 placed: **2 + 5 + 3 + 5**.',
          wrong: 'That’s the {point}-point. The 6-point is in your home board, right next to the bar.',
        },
        {
          id: 'mirror',
          kind: 'explain',
          title: 'Ready to play',
          text: 'Your opponent’s checkers mirror yours. This is the **starting position**.',
          board: { position: START },
        },
        {
          id: 'quiz-back',
          kind: 'choice',
          prompt: 'Where do your **2 back checkers** start?',
          board: { position: START, showPointNumbers: false },
          options: [
            {
              id: '24',
              text: 'On the 24-point',
              correct: true,
              explanation: 'Yes: two checkers on the 24-point, deep in your opponent’s home board.',
            },
            {
              id: '13',
              text: 'On the 13-point',
              explanation: 'The 13-point holds five checkers, your mid-point. The two back checkers start on the 24-point.',
            },
            {
              id: '1',
              text: 'On the 1-point',
              explanation: 'The two dark checkers on your 1-point are your opponent’s back checkers. Yours are on the 24-point.',
            },
          ],
        },
      ],
    },
  ],
};
