import { highlightPoint, highlightPoints, pointTargets, START } from '../builders';
import type { Section } from '../types';

/**
 * Standard opening plays (they match OPENING_PLAYS in the AI's opening book).
 * Where strong players disagree, every popular choice is accepted.
 */
export const openingsSection: Section = {
  id: 'openings',
  title: 'Opening Moves',
  subtitle: 'The best start for every roll',
  icon: 'book-open-page-variant',
  color: '#818CF8',
  goal: 'Play a strong first move with any roll.',
  lessons: [
    {
      id: 'openings-1',
      sectionId: 'openings',
      title: 'Point-Making Rolls',
      description: 'The four rolls that make a point at once.',
      icon: 'star-shooting',
      difficulty: 3,
      category: 'opening',
      passingScore: 0.6,
      xp: 25,
      objectives: [
        { id: 'first', text: 'Know how the first move is decided' },
        { id: 'points', text: 'Make a point with 3-1, 4-2, 6-1 and 5-3' },
      ],
      steps: [
        {
          id: 'first-roll',
          kind: 'explain',
          title: 'The opening roll',
          text: 'To start, each player rolls **one die**. The higher number moves first and plays **both** numbers.',
          tip: 'That’s why your first move is never a double.',
          board: { position: START },
        },
        {
          id: 'best-rolls',
          kind: 'explain',
          title: 'The best rolls',
          text: '**3-1**, **4-2**, **6-1** and **5-3** make a new point straight away. Every other roll has to compromise.',
          board: { position: START, highlights: [highlightPoints([7, 5, 4, 3], 'gold', 'New points')] },
        },
        {
          id: 'four-two',
          kind: 'move',
          prompt: 'You rolled **4-2**. Make your **4-point**.',
          board: { position: START, dice: [4, 2], highlights: [highlightPoint(4, 'gold')] },
          goal: { type: 'make-point', point: 4 },
          solution: '8/4 6/4',
          correct: 'Point made! 8/4 6/4 adds a second strong point to your home board.',
          wrong: 'Play the 4 from your 8-point and the 2 from your 6-point: both land on the 4-point.',
          wrongPlays: [
            {
              plays: ['13/9 13/11'],
              text: 'Two builders is a fine idea, but 4-2 can make a point right now: 8/4 6/4.',
            },
          ],
        },
        {
          id: 'five-three',
          kind: 'move',
          prompt: 'You rolled **5-3**. Find the new point this roll makes.',
          board: { position: START, dice: [5, 3] },
          goal: { type: 'make-point', point: 3 },
          solution: '8/3 6/3',
          correct: '8/3 6/3. The 3-point is deep, but it’s still a safe point that blocks.',
          wrong: 'A 5 from the 8-point and a 3 from the 6-point both reach your 3-point.',
          wrongPlays: [
            {
              plays: ['13/8 13/10'],
              text: 'A reasonable move, but 5-3 can make a new point: 8/3 6/3.',
            },
          ],
        },
        {
          id: 'six-one',
          kind: 'tap',
          prompt: 'With **6-1**, which point do you make? Tap it.',
          board: { position: START, dice: [6, 1] },
          answers: pointTargets(7),
          correct: 'The 7-point, called the bar point: 13/7 8/7. It blocks 6s from their back checkers.',
          wrong: 'A 6 from the 13-point and a 1 from the 8-point meet on the 7-point.',
        },
        {
          id: 'no-point',
          kind: 'choice',
          prompt: 'Which of these opening rolls **can’t** make a new point?',
          options: [
            { id: '3-1', text: '3-1', explanation: '3-1 makes your 5-point: 8/5 6/5. It’s the best opening roll.' },
            { id: '4-2', text: '4-2', explanation: '4-2 makes your 4-point: 8/4 6/4.' },
            {
              id: '6-5',
              text: '6-5',
              correct: true,
              explanation: 'Right. 6-5 makes no point, but it runs a back checker all the way to safety: 24/13.',
            },
            { id: '6-1', text: '6-1', explanation: '6-1 makes your 7-point: 13/7 8/7.' },
          ],
        },
      ],
    },
    {
      id: 'openings-2',
      sectionId: 'openings',
      title: 'Split or Build',
      description: 'What to do when you can’t make a point.',
      icon: 'directions-fork',
      difficulty: 3,
      category: 'opening',
      passingScore: 0.6,
      xp: 25,
      objectives: [
        { id: 'run', text: 'Run with 6-5' },
        { id: 'split', text: 'Split your back checkers' },
        { id: 'build', text: 'Bring builders down' },
      ],
      steps: [
        {
          id: 'plans',
          kind: 'explain',
          title: 'No point to make?',
          text: 'Then you have three plans: **run** a back checker, **split** your back checkers, or bring **builders** down.',
          board: {
            position: START,
            highlights: [highlightPoint(24, 'info', 'Run or split'), highlightPoint(13, 'gold', 'Builders')],
          },
        },
        {
          id: 'six-five',
          kind: 'choice',
          prompt: 'Your opening roll is **6-5**. Which plan is best?',
          board: { position: START, dice: [6, 5] },
          options: [
            {
              id: 'run',
              text: 'Run: 24/13',
              play: '24/13',
              correct: true,
              explanation: 'Yes! 24/13, the “lover’s leap”, takes a back checker all the way to safety.',
            },
            {
              id: 'build',
              text: 'Build: 13/7 13/8',
              play: '13/7 13/8',
              explanation: 'That leaves a blot on 7 and both back checkers still stuck. Running 24/13 is much stronger.',
            },
            {
              id: 'split',
              text: 'Split: 24/18 13/8',
              play: '24/18 13/8',
              explanation: 'Not bad, but 6-5 can bring a back checker all the way home in one go: 24/13.',
            },
          ],
        },
        {
          id: 'split',
          kind: 'explain',
          title: 'Splitting',
          text: 'Moving one back checker up **splits** them. Split checkers make an **anchor** more easily, but they can be hit.',
          board: {
            position: { player1: { 24: 1, 21: 1, 13: 4, 11: 1, 8: 3, 6: 5 }, player2: START.player2 },
            highlights: [highlightPoints([24, 21], 'info', 'Split')],
          },
        },
        {
          id: 'four-three',
          kind: 'move',
          prompt: 'You rolled **4-3**. **Split** a back checker and bring one builder down.',
          board: { position: START, dice: [4, 3] },
          goal: { type: 'plays', plays: ['24/20 13/10', '24/21 13/9'] },
          solution: '24/20 13/10',
          correct: 'A split and a builder: next turn you can make an anchor or a new point.',
          wrong: 'Play one die with a back checker on 24 and the other from your mid-point on 13.',
          wrongPlays: [
            {
              plays: ['13/10 13/9'],
              text: 'Two builders is a good opening too, but here we wanted a split: one back checker, one builder.',
            },
            {
              plays: ['24/20 24/21'],
              text: 'Splitting both back checkers leaves two blots in their home. Split one and bring a builder down.',
            },
          ],
        },
        {
          id: 'builders',
          kind: 'explain',
          title: 'Builders',
          text: 'Checkers up to 6 pips above a point you want are **builders**. More builders, more rolls that make the point.',
          board: {
            position: { player1: { 24: 2, 13: 3, 11: 1, 8: 4, 6: 5 }, player2: START.player2 },
            highlights: [highlightPoints([11, 8], 'info', 'Builders'), highlightPoints([7, 5, 4], 'gold')],
          },
        },
        {
          id: 'five-two',
          kind: 'move',
          prompt: 'You rolled **5-2**. Bring **two builders** down from your mid-point.',
          board: { position: START, dice: [5, 2] },
          goal: { type: 'plays', plays: ['13/8 13/11'] },
          solution: '13/8 13/11',
          correct: '13/8 13/11. Next turn, lots of rolls make your 5-, 4- or 7-point.',
          wrong: 'Move one mid-point checker 5 to the 8-point and another 2 to the 11-point.',
          wrongPlays: [
            {
              plays: ['13/6'],
              text: 'Safe, but that brings down just one checker. Use both dice from the mid-point.',
            },
          ],
        },
        {
          id: 'why-split',
          kind: 'choice',
          prompt: 'Why split your back checkers early in the game?',
          options: [
            {
              id: 'anchor',
              text: 'It’s easier to make an anchor',
              correct: true,
              explanation: 'Right. Split checkers cover more numbers, so making an advanced anchor gets easier.',
            },
            {
              id: 'safe',
              text: 'It keeps them completely safe',
              explanation: 'The opposite: split checkers are blots. You accept a little risk for flexibility.',
            },
            {
              id: 'race',
              text: 'It wins the race',
              explanation: 'A split moves only a few pips. It’s about flexibility, not the race.',
            },
          ],
        },
      ],
    },
    {
      id: 'openings-3',
      sectionId: 'openings',
      title: 'Opening Quiz',
      description: 'A strong first move for any roll.',
      icon: 'school',
      difficulty: 4,
      category: 'opening',
      passingScore: 0.6,
      xp: 40,
      objectives: [
        { id: 'any', text: 'Choose a strong move for any opening roll' },
        { id: 'pass', text: 'Score 60% or more to pass' },
      ],
      steps: [
        {
          id: 'intro',
          kind: 'explain',
          title: 'Opening quiz',
          text: 'Find a strong first move for each roll. Some rolls have **two or three** good choices: any of them counts.',
          board: { position: START },
        },
        {
          id: 'two-one',
          kind: 'move',
          prompt: 'Opening roll: **2-1**. Your move.',
          board: { position: START, dice: [2, 1] },
          goal: { type: 'plays', plays: ['13/11 6/5', '24/23 13/11'] },
          solution: '13/11 6/5',
          correct: 'Good. A builder to 11, then slot the 5-point (6/5) or split (24/23): both are standard.',
          wrong: 'Small rolls bring a builder down (13/11) and slot 6/5 or split 24/23.',
          coachFeedback: true,
        },
        {
          id: 'six-four',
          kind: 'move',
          prompt: 'Opening roll: **6-4**. Your move.',
          board: { position: START, dice: [6, 4] },
          goal: { type: 'plays', plays: ['24/18 13/9', '24/14', '8/2 6/2'] },
          solution: '24/18 13/9',
          correct: 'Nice. 6-4 has three good plays: split with 24/18 13/9, run 24/14, or make the 2-point.',
          wrong: 'Try splitting 24/18 with a builder 13/9, running 24/14, or making the 2-point: 8/2 6/2.',
          coachFeedback: true,
        },
        {
          id: 'six-three',
          kind: 'move',
          prompt: 'Opening roll: **6-3**. Your move.',
          board: { position: START, dice: [6, 3] },
          goal: { type: 'plays', plays: ['24/18 13/10', '24/15'] },
          solution: '24/18 13/10',
          correct: 'Well played. Split to 18 with a builder to 10, or run 24/15: both are fine.',
          wrong: 'With 6-3, split 24/18 and bring a builder 13/10, or run a back checker 24/15.',
          coachFeedback: true,
        },
        {
          id: 'five-four',
          kind: 'move',
          prompt: 'Opening roll: **5-4**. Your move.',
          board: { position: START, dice: [5, 4] },
          goal: { type: 'plays', plays: ['24/20 13/8', '13/8 13/9'] },
          solution: '24/20 13/8',
          correct: 'Good. 13/8 is safe, and the 4 either splits (24/20) or brings a builder (13/9).',
          wrong: 'Play the 5 safely with 13/8. The 4 then splits 24/20 or brings a builder 13/9.',
          coachFeedback: true,
        },
        {
          id: 'three-two',
          kind: 'move',
          prompt: 'Opening roll: **3-2**. Your move.',
          board: { position: START, dice: [3, 2] },
          goal: { type: 'plays', plays: ['24/21 13/11', '13/10 13/11'] },
          solution: '24/21 13/11',
          correct: 'Good. A builder to 11 plus a split (24/21) or a second builder (13/10).',
          wrong: 'Bring a builder 13/11 with the 2. The 3 splits 24/21 or brings another builder 13/10.',
          coachFeedback: true,
        },
        {
          id: 'six-one',
          kind: 'move',
          prompt: 'And one point-maker to finish. Opening roll: **6-1**.',
          board: { position: START, dice: [6, 1] },
          goal: { type: 'plays', plays: ['13/7 8/7'] },
          solution: '13/7 8/7',
          correct: 'The bar point! 13/7 8/7 starts a wall in front of their back checkers.',
          wrong: '6-1 makes the 7-point: a 6 from your mid-point and a 1 from your 8-point.',
          coachFeedback: true,
        },
      ],
    },
  ],
};
