import { highlightPoint, quadrant } from '../builders';
import type { Section } from '../types';

export const bearingOffSection: Section = {
  id: 'bearing-off',
  title: 'Bearing Off',
  subtitle: 'Bring them home, take them off',
  icon: 'home-export-outline',
  color: '#F3B847',
  goal: 'Bear off all your checkers efficiently.',
  lessons: [
    {
      id: 'bearoff-1',
      sectionId: 'bearing-off',
      title: 'Coming Home',
      description: 'Everyone home before anyone leaves.',
      icon: 'home-import-outline',
      difficulty: 2,
      category: 'bearing-off',
      passingScore: 0,
      xp: 20,
      objectives: [
        { id: 'all-home', text: 'Know when you may start bearing off' },
        { id: 'bring', text: 'Bring your last checkers home' },
      ],
      steps: [
        {
          id: 'rule',
          kind: 'explain',
          title: 'All 15 at home',
          text: 'You can only start **bearing off** once **all 15** of your checkers are in your home board.',
          board: {
            position: { player1: { 6: 3, 5: 3, 4: 3, 3: 2, 2: 2, 1: 2 }, player2: { 19: 5, 20: 5, 22: 5 } },
            highlights: [quadrant('player1-home', 'gold', 'All home!')],
          },
        },
        {
          id: 'can-start',
          kind: 'choice',
          prompt: 'Can you start bearing off in this position?',
          board: {
            position: { player1: { 8: 1, 6: 3, 5: 3, 4: 2, 3: 2, 2: 2, 1: 2 }, player2: { 19: 5, 20: 5, 22: 5 } },
            highlights: [highlightPoint(8, 'danger')],
          },
          options: [
            {
              id: 'no',
              text: 'Not yet: one checker is still outside',
              correct: true,
              explanation: 'Right. The checker on the 8-point has to come home first.',
            },
            {
              id: 'yes',
              text: 'Yes, almost everyone is home',
              explanation: 'Almost isn’t enough. Every single checker must be in your home board, and one is still on the 8-point.',
            },
          ],
        },
        {
          id: 'bring-home',
          kind: 'move',
          prompt: 'You rolled a **3**. Bring your last checker home.',
          board: {
            position: { player1: { 8: 1, 6: 3, 5: 3, 4: 2, 3: 2, 2: 2, 1: 2 }, player2: { 19: 5, 20: 5, 22: 5 } },
            dice: [3],
          },
          goal: { type: 'land-on', point: 5, count: 4 },
          solution: '8/5',
          correct: 'Everyone is home. From your next roll on, you can start bearing off.',
          wrong: 'Move the checker on the 8-point: three spaces takes it to the 5-point, inside your home board.',
        },
      ],
    },
    {
      id: 'bearoff-2',
      sectionId: 'bearing-off',
      title: 'Taking Checkers Off',
      description: 'Each number removes a checker from its point.',
      icon: 'tray-arrow-up',
      difficulty: 2,
      category: 'bearing-off',
      passingScore: 0,
      xp: 20,
      objectives: [
        { id: 'exact', text: 'Bear off with exact numbers' },
        { id: 'inside', text: 'Move inside your home board' },
      ],
      steps: [
        {
          id: 'how',
          kind: 'demo',
          title: 'Bearing off',
          text: 'Roll a **4** and you can remove a checker from your **4-point**. A **2** removes one from the **2-point**.',
          board: { position: { player1: { 6: 2, 4: 3, 2: 2 }, player2: { 20: 4 } }, dice: [4, 2] },
          moves: [
            { from: 4, to: 'off', caption: 'The 4 bears off from the 4-point…' },
            { from: 2, to: 'off', caption: '…and the 2 from the 2-point.' },
          ],
        },
        {
          id: 'exact',
          kind: 'move',
          prompt: 'You rolled **5-3**. Bear off **two** checkers.',
          board: { position: { player1: { 6: 2, 5: 2, 3: 2, 1: 1 }, player2: { 20: 4 } }, dice: [5, 3] },
          goal: { type: 'bear-off', count: 2 },
          solution: '5/off 3/off',
          correct: 'Two off! Tap a checker, then the tray on the right to bear it off.',
          wrong: 'Use each number on its own point: the 5 on the 5-point and the 3 on the 3-point.',
        },
        {
          id: 'move-inside',
          kind: 'explain',
          title: 'You can also move',
          text: 'You don’t have to bear off: you can move a checker **inside** your home board instead.',
          board: { position: { player1: { 6: 2, 5: 1, 2: 2 }, player2: { 20: 4 } }, dice: [4, 1] },
        },
        {
          id: 'no-checker',
          kind: 'move',
          prompt: 'You rolled a **2**, but your 2-point is empty. Play the 2.',
          board: { position: { player1: { 6: 2, 5: 2, 4: 1 }, player2: { 20: 4 } }, dice: [2] },
          goal: { type: 'any' },
          solution: '6/4',
          correct: 'Right. With nothing on the 2-point (and checkers higher up) you move a checker 2 spaces instead.',
          wrong: 'Move any checker 2 spaces inside your home board.',
        },
      ],
    },
    {
      id: 'bearoff-3',
      sectionId: 'bearing-off',
      title: 'Bigger Numbers',
      description: 'What to do with a roll that overshoots.',
      icon: 'arrow-collapse-up',
      difficulty: 3,
      category: 'bearing-off',
      passingScore: 0.5,
      xp: 25,
      objectives: [
        { id: 'high', text: 'Use big numbers from your highest point' },
        { id: 'higher-first', text: 'Know when a big number must move instead' },
        { id: 'finish', text: 'Bear off a whole position' },
      ],
      steps: [
        {
          id: 'highest',
          kind: 'explain',
          title: 'Overshooting',
          text: 'Roll **higher** than your highest checker? Bear off from your **highest point** instead.',
          board: {
            position: { player1: { 4: 2, 3: 1 }, player2: { 20: 4 } },
            highlights: [highlightPoint(4, 'gold', 'Highest')],
            dice: [6, 5],
          },
        },
        {
          id: 'overshoot',
          kind: 'move',
          prompt: 'You rolled **6-5**. Bear off two checkers.',
          board: { position: { player1: { 4: 2, 3: 1 }, player2: { 20: 4 } }, dice: [6, 5] },
          goal: { type: 'bear-off', count: 2 },
          solution: '4/off(2)',
          correct: 'Both big numbers came off your highest point, the 4-point.',
          wrong: 'Big numbers bear off from the highest point you still have.',
        },
        {
          id: 'higher-first',
          kind: 'explain',
          title: 'Unless someone is higher',
          text: 'If a checker sits **higher** than the number, you can’t bear off a lower one. You must move a higher checker.',
          board: {
            position: { player1: { 6: 1, 3: 2 }, player2: { 20: 4 } },
            highlights: [highlightPoint(6, 'gold')],
            dice: [5],
          },
        },
        {
          id: 'must-move',
          kind: 'move',
          prompt: 'You rolled a **5**. Play it.',
          board: { position: { player1: { 6: 1, 3: 2 }, player2: { 20: 4 } }, dice: [5] },
          goal: { type: 'land-on', point: 1 },
          solution: '6/1',
          correct: 'Right. The checker on the 6-point is higher than 5, so you must move it: 6/1.',
          wrong: 'With a checker on the 6-point, the 5 can’t bear off from lower down. Move the 6-point checker.',
        },
        {
          id: 'challenge',
          kind: 'challenge',
          prompt: 'Bear off all **6 checkers** in just **3 rolls**!',
          board: { position: { player1: { 5: 2, 4: 2, 2: 2 }, player2: { 20: 4 }, off: { player1: 9 } } },
          rolls: [
            [6, 5],
            [4, 2],
            [4, 2],
          ],
          goal: { type: 'bear-off-all' },
          success: 'All home and all off! You’d win this race.',
          failure: 'So close! Use each roll to take checkers off. Big numbers clear your highest points first.',
        },
      ],
    },
  ],
};
