import { highlightPoint, highlightPoints, pointTargets, START } from '../builders';
import type { Section } from '../types';

export const movingSection: Section = {
  id: 'moving',
  title: 'Moving Checkers',
  subtitle: 'Dice, doubles and legal moves',
  icon: 'dice-multiple',
  color: '#3DD68C',
  goal: 'Move checkers correctly with any roll.',
  lessons: [
    {
      id: 'moving-1',
      sectionId: 'moving',
      title: 'Rolling the Dice',
      description: 'Two dice, two separate moves.',
      icon: 'dice-5',
      difficulty: 1,
      category: 'movement',
      passingScore: 0,
      xp: 15,
      objectives: [
        { id: 'two-moves', text: 'Treat each die as its own move' },
        { id: 'combine', text: 'Move one checker with both dice' },
        { id: 'first-turn', text: 'Know who plays first' },
      ],
      steps: [
        {
          id: 'two-dice',
          kind: 'explain',
          title: 'Two dice',
          text: 'Each turn you roll **two dice**. Each die is a **separate move**.',
          board: { position: START, dice: [5, 2] },
        },
        {
          id: 'one-die',
          kind: 'move',
          prompt: 'First, just one die. Move your checker **4** spaces.',
          board: { position: { player1: { 13: 1 }, player2: { 19: 2 } }, dice: [4] },
          goal: { type: 'land-on', point: 9 },
          solution: '13/9',
          correct: 'Right. Four spaces from the 13-point is the 9-point.',
          wrong: 'Count four points toward home: 12, 11, 10, 9.',
        },
        {
          id: 'both-dice-one-checker',
          kind: 'move',
          prompt: 'Now you rolled **4** and **2**. Move this one checker by **both** numbers.',
          board: { position: { player1: { 13: 1 }, player2: { 19: 2 } }, dice: [4, 2] },
          goal: { type: 'land-on', point: 7 },
          solution: '13/7',
          correct: 'Perfect: 4 + 2 = 6 spaces. One checker can use both dice.',
          wrong: 'Use both numbers on the same checker: 4 + 2 = 6 spaces from the 13-point.',
          hint: 'You can tap the 7-point directly: the checker uses both dice.',
        },
        {
          id: 'sum-question',
          kind: 'choice',
          prompt: 'You roll **5** and **3**. How far can one checker travel using both?',
          options: [
            { id: '5', text: '5 spaces', explanation: 'That only uses one die. Add them: 5 + 3 = 8.' },
            {
              id: '8',
              text: '8 spaces',
              correct: true,
              explanation: 'Yes: 5 + 3 = 8, as long as it can stop on the point in between.',
            },
            { id: '15', text: '15 spaces', explanation: 'Dice are added, not multiplied: 5 + 3 = 8.' },
          ],
        },
        {
          id: 'two-checkers',
          kind: 'move',
          prompt: 'You rolled **6** and **1**. Play each number with a **different** checker.',
          board: { position: { player1: { 13: 1, 8: 1 }, player2: { 19: 2 } }, dice: [6, 1] },
          goal: { type: 'plays', plays: ['13/7 8/7', '13/12 8/2'] },
          solution: '13/7 8/7',
          correct: 'Nice. Each die can move a different checker. Here they even landed together on the 7-point!',
          wrong: 'That moved one checker with both dice. This time use the 6 on one checker and the 1 on the other.',
        },
        {
          id: 'who-starts',
          kind: 'explain',
          title: 'The first roll',
          text: 'To start, each player rolls **one die**. The higher number goes first and plays **both** dice.',
          board: { position: START, dice: [6, 4] },
          tip: 'If both dice match, you both roll again.',
        },
      ],
    },
    {
      id: 'moving-2',
      sectionId: 'moving',
      title: 'Doubles',
      description: 'Same number twice? Move four times!',
      icon: 'dice-6',
      difficulty: 1,
      category: 'movement',
      passingScore: 0,
      xp: 15,
      objectives: [
        { id: 'four', text: 'Play doubles four times' },
        { id: 'total', text: 'Add up a double’s total' },
      ],
      steps: [
        {
          id: 'what',
          kind: 'explain',
          title: 'Doubles',
          text: 'Roll the same number twice and you get **doubles**: play that number **four times**.',
          board: { position: START, dice: [3, 3] },
        },
        {
          id: 'four-checkers',
          kind: 'move',
          prompt: 'You rolled **3-3**. Play all **four** 3s.',
          board: { position: { player1: { 13: 2, 8: 2 }, player2: { 19: 2 } }, dice: [3, 3] },
          goal: { type: 'any' },
          solution: '13/10(2) 8/5(2)',
          correct: 'Four moves from one roll. Doubles are powerful!',
          wrong: 'Keep going until all four 3s are played.',
        },
        {
          id: 'one-checker',
          kind: 'move',
          prompt: 'You rolled **2-2**. Move this checker as far as it can go: **8 spaces**.',
          board: { position: { player1: { 10: 1 }, player2: { 19: 2 } }, dice: [2, 2] },
          goal: { type: 'land-on', point: 2 },
          solution: '10/2',
          correct: '2 + 2 + 2 + 2 = 8. From the 10-point to the 2-point.',
          wrong: 'Use all four 2s on this checker: 10 → 8 → 6 → 4 → 2.',
        },
        {
          id: 'total',
          kind: 'choice',
          prompt: 'You roll **5-5**. How many spaces can you move in total?',
          options: [
            { id: '10', text: '10', explanation: 'That would be a normal roll. Doubles count four times: 4 × 5 = 20.' },
            { id: '20', text: '20', correct: true, explanation: 'Right: four moves of 5 is 20 spaces.' },
            { id: '25', text: '25', explanation: 'Close, but doubles give four moves, not five: 4 × 5 = 20.' },
          ],
        },
      ],
    },
    {
      id: 'moving-3',
      sectionId: 'moving',
      title: 'Open & Blocked Points',
      description: 'Where you can land, and where you can’t.',
      icon: 'cancel',
      difficulty: 2,
      category: 'movement',
      passingScore: 0,
      xp: 15,
      objectives: [
        { id: 'open', text: 'Know which points are open' },
        { id: 'blocked', text: 'Spot blocked points' },
      ],
      steps: [
        {
          id: 'open',
          kind: 'explain',
          title: 'Open points',
          text: 'You can land on an **empty** point or a point that already has **your** checkers.',
          board: {
            position: { player1: { 13: 1, 9: 2 }, player2: { 19: 2 } },
            highlights: [highlightPoint(10, 'success', 'Empty'), highlightPoint(9, 'success', 'Yours')],
          },
        },
        {
          id: 'blocked',
          kind: 'explain',
          title: 'Blocked points',
          text: 'A point with **two or more** of your opponent’s checkers is **blocked**. You can’t land there.',
          board: {
            position: { player1: { 13: 1 }, player2: { 9: 2, 19: 2 } },
            highlights: [highlightPoint(9, 'danger', 'Blocked')],
          },
        },
        {
          id: 'can-move',
          kind: 'choice',
          prompt: 'Can the checker on the **13-point** move **4**?',
          board: {
            position: { player1: { 13: 1 }, player2: { 9: 2, 19: 2 } },
            highlights: [highlightPoint(13, 'gold')],
            dice: [4],
          },
          options: [
            {
              id: 'no',
              text: 'No, the 9-point is blocked',
              correct: true,
              explanation: 'Exactly. 13 − 4 = 9, and two dark checkers hold the 9-point.',
            },
            {
              id: 'yes',
              text: 'Yes, it moves to the 9-point',
              explanation: 'Look again: two dark checkers sit on the 9-point, so it’s blocked.',
            },
          ],
        },
        {
          id: 'which-checker',
          kind: 'tap',
          prompt: 'You rolled a **5**. Only one checker can move. Tap it.',
          board: {
            position: { player1: { 13: 1, 10: 1, 7: 1 }, player2: { 8: 2, 5: 2, 19: 2 } },
            dice: [5],
          },
          answers: pointTargets(7),
          correct: 'Yes! 7 − 5 = 2, an empty point. The others would land on blocked points.',
          wrong: 'That checker would land on a blocked point. Check each one: 13 → 8, 10 → 5, 7 → 2.',
          wrongCases: [
            {
              targets: pointTargets(8, 5, 19),
              text: 'Those are your opponent’s checkers. Tap one of your light checkers.',
            },
          ],
        },
        {
          id: 'find-legal',
          kind: 'move',
          prompt: 'You rolled **5-4**. Find a way to play **both** numbers.',
          board: {
            position: { player1: { 13: 1, 6: 1 }, player2: { 8: 2, 2: 2, 19: 2 } },
            highlights: [highlightPoints([8, 2], 'danger')],
            dice: [5, 4],
          },
          goal: { type: 'any' },
          solution: '13/9 6/1',
          correct: 'Well found. The glowing spots always show where a checker can legally land.',
          wrong: 'Try a different order: one route is blocked, the other is open.',
        },
      ],
    },
    {
      id: 'moving-4',
      sectionId: 'moving',
      title: 'Using Every Roll',
      description: 'The rules for playing both dice.',
      icon: 'scale-balance',
      difficulty: 2,
      category: 'movement',
      passingScore: 0.5,
      xp: 20,
      objectives: [
        { id: 'both', text: 'Play both dice whenever you can' },
        { id: 'larger', text: 'Play the larger die if only one fits' },
        { id: 'dance', text: 'Know what happens when nothing can move' },
      ],
      steps: [
        {
          id: 'rule',
          kind: 'explain',
          title: 'Use your whole roll',
          text: 'You **must** play both numbers if you can, even if you’d rather not.',
          board: { position: START, dice: [6, 5] },
        },
        {
          id: 'order',
          kind: 'move',
          prompt: 'You rolled **6-5**. The 6 is blocked from the 24-point. Find a way to play **both**.',
          board: {
            position: { player1: { 24: 1 }, player2: { 18: 2, 12: 2 } },
            highlights: [highlightPoint(18, 'danger', 'Blocked')],
            dice: [6, 5],
          },
          goal: { type: 'plays', plays: ['24/13'] },
          solution: '24/13',
          correct: 'Play the 5 first: from the 19-point, the 6 is open. Order matters!',
          wrong: 'Try the 5 first, then the 6 from where you land.',
        },
        {
          id: 'larger',
          kind: 'explain',
          title: 'Only one fits?',
          text: 'If you can play **only one** of the numbers, you must play the **larger** one if possible.',
          board: { position: { player1: { 13: 1 }, player2: { 4: 2, 19: 2 } }, dice: [6, 3] },
        },
        {
          id: 'larger-move',
          kind: 'move',
          prompt: 'You rolled **6-3**. Only one die can be played. Which one? Play it.',
          board: {
            position: { player1: { 13: 1 }, player2: { 4: 2, 19: 2 } },
            highlights: [highlightPoint(4, 'danger', 'Blocked')],
            dice: [6, 3],
          },
          goal: { type: 'land-on', point: 7 },
          solution: '13/7',
          correct: 'Right: 13/7. After either move the other die is blocked, so the larger number must be played.',
          wrong: 'When only one die can be played, the rule says play the larger one.',
        },
        {
          id: 'dance',
          kind: 'choice',
          prompt: 'If **none** of your checkers can move, what happens?',
          options: [
            {
              id: 'lose',
              text: 'Your turn passes',
              correct: true,
              explanation: 'Yes. You simply can’t move this turn. Players call it “dancing”.',
            },
            {
              id: 'reroll',
              text: 'You roll again',
              explanation: 'No re-rolls in backgammon. If nothing can move, your turn passes.',
            },
            {
              id: 'back',
              text: 'You move backwards instead',
              explanation: 'Checkers never move backwards. If nothing can move, your turn passes.',
            },
          ],
        },
      ],
    },
  ],
};
