import { highlightPoint, pointTargets, quadrant, START } from '../builders';
import type { Section } from '../types';

export const winningSection: Section = {
  id: 'winning',
  title: 'Winning Games',
  subtitle: 'Singles, gammons and backgammons',
  icon: 'trophy',
  color: '#FF6B8A',
  goal: 'Know what a win is worth.',
  lessons: [
    {
      id: 'winning-1',
      sectionId: 'winning',
      title: 'Gammons & Backgammons',
      description: 'Some wins count double, or triple.',
      icon: 'trophy-variant',
      difficulty: 2,
      category: 'scoring',
      passingScore: 0.5,
      xp: 20,
      objectives: [
        { id: 'single', text: 'A normal win is worth 1 point' },
        { id: 'gammon', text: 'Spot a gammon (2 points)' },
        { id: 'backgammon', text: 'Spot a backgammon (3 points)' },
      ],
      steps: [
        {
          id: 'single',
          kind: 'explain',
          title: 'A win',
          text: 'Bear off all 15 checkers first and you **win**. A normal win is worth **1 point**.',
          board: {
            position: { player2: { 19: 3, 21: 2 }, off: { player1: 15, player2: 10 } },
            highlights: [{ region: { kind: 'off' }, tone: 'gold' }],
          },
        },
        {
          id: 'gammon',
          kind: 'explain',
          title: 'Gammon: 2 points',
          text: 'If your opponent hasn’t borne off **a single checker** when you finish, that’s a **gammon**: worth **2 points**.',
          board: {
            position: { player2: { 19: 5, 20: 4, 22: 3, 15: 3 }, off: { player1: 15 } },
            highlights: [quadrant('player2-home', 'danger', 'Nothing borne off')],
          },
        },
        {
          id: 'backgammon',
          kind: 'explain',
          title: 'Backgammon: 3 points',
          text: 'Worse still: no checkers off **and** a checker in your home board or on the bar. That’s a **backgammon**: **3 points**.',
          board: {
            position: { player2: { 19: 5, 20: 5, 13: 4, 3: 1 }, off: { player1: 15 } },
            highlights: [highlightPoint(3, 'danger', 'Still in your home')],
          },
        },
        {
          id: 'quiz-single',
          kind: 'choice',
          prompt: 'You just bore off your last checker. How many points do you win?',
          board: { position: { player2: { 20: 3, 22: 2 }, off: { player1: 15, player2: 10 } } },
          options: [
            { id: '1', text: '1 point', correct: true, explanation: 'Right: your opponent bore off 10 checkers, so it’s a normal win.' },
            { id: '2', text: '2 points (gammon)', explanation: 'A gammon needs your opponent to have borne off nothing. They have 10 off.' },
            { id: '3', text: '3 points (backgammon)', explanation: 'They’ve borne off checkers, so it’s just a single win: 1 point.' },
          ],
        },
        {
          id: 'quiz-gammon',
          kind: 'choice',
          prompt: 'You just bore off your last checker. How many points do you win?',
          board: { position: { player2: { 19: 6, 21: 5, 18: 4 }, off: { player1: 15 } } },
          options: [
            { id: '1', text: '1 point', explanation: 'Your opponent has nothing borne off, which makes this a gammon.' },
            { id: '2', text: '2 points (gammon)', correct: true, explanation: 'Yes! Nothing borne off, but nothing in your home board either: a gammon.' },
            { id: '3', text: '3 points (backgammon)', explanation: 'For a backgammon they’d also need a checker in your home board or on the bar.' },
          ],
        },
        {
          id: 'quiz-backgammon',
          kind: 'choice',
          prompt: 'One last time: what does this win score?',
          board: { position: { player2: { 19: 6, 20: 6, 12: 2 }, bar: { player2: 1 }, off: { player1: 15 } } },
          options: [
            { id: '1', text: '1 point', explanation: 'They’ve borne off nothing and have a checker on the bar. That’s much more than a single win.' },
            { id: '2', text: '2 points (gammon)', explanation: 'Look at the bar: a checker stuck there turns a gammon into a backgammon.' },
            { id: '3', text: '3 points (backgammon)', correct: true, explanation: 'Backgammon! No checkers off and one still on the bar.' },
          ],
        },
      ],
    },
    {
      id: 'winning-2',
      sectionId: 'winning',
      title: 'Rules Checkpoint',
      description: 'Show you know the whole game.',
      icon: 'flag-checkered',
      difficulty: 3,
      category: 'movement',
      passingScore: 0.6,
      xp: 40,
      objectives: [
        { id: 'all', text: 'Combine every rule you’ve learned' },
        { id: 'pass', text: 'Score 60% or more to pass' },
      ],
      steps: [
        {
          id: 'intro',
          kind: 'explain',
          title: 'Checkpoint',
          text: 'Time to put it all together. Get **60%** right to pass. You’ve got this!',
          board: { position: START },
        },
        {
          id: 'setup',
          kind: 'tap',
          prompt: 'Where do your **five mid-point checkers** start?',
          board: { position: { player1: { 24: 2, 8: 3, 6: 5 }, player2: { 1: 2, 12: 5, 17: 3, 19: 5 } } },
          answers: pointTargets(13),
          correct: 'Yes, the 13-point: your mid-point.',
          wrong: 'Your five mid-point checkers start on the 13-point, top left.',
        },
        {
          id: 'enter-hit',
          kind: 'move',
          prompt: 'You’re on the bar and rolled **4-3**. Enter **and** hit the blot on the 21-point.',
          board: {
            position: { player1: { 13: 4, 8: 3, 6: 5, 5: 2 }, player2: { 21: 1, 19: 4, 12: 4, 17: 3, 1: 2 }, bar: { player1: 1 } },
            dice: [4, 3],
          },
          goal: { type: 'hit', point: 21 },
          solution: 'bar/21* 13/10',
          correct: 'In and hitting! A 4 enters on the 21-point, right on top of their blot.',
          wrong: 'A 4 enters on the 21-point (25 − 4), exactly where their blot sits.',
        },
        {
          id: 'doubles',
          kind: 'move',
          prompt: 'You rolled **6-6**. Make your 18-point **and** your 7-point.',
          board: { position: START, dice: [6, 6] },
          goal: { type: 'plays', plays: ['24/18(2) 13/7(2)'] },
          solution: '24/18(2) 13/7(2)',
          correct: 'The best opening double: two strong points in one roll.',
          wrong: 'Move both back checkers 6 to the 18-point, and two mid-point checkers 6 to the 7-point.',
        },
        {
          id: 'bear-off',
          kind: 'move',
          prompt: 'You rolled **6-2**. Bear off two checkers.',
          board: { position: { player1: { 5: 1, 3: 2, 2: 1 }, player2: { 21: 4 }, off: { player1: 11 } }, dice: [6, 2] },
          goal: { type: 'bear-off', count: 2 },
          solution: '5/off 2/off',
          correct: 'The 6 took off your highest checker and the 2 was exact.',
          wrong: 'A 6 bears off from your highest point (the 5-point); the 2 bears off from the 2-point.',
        },
        {
          id: 'score',
          kind: 'choice',
          prompt: 'You win while your opponent still has all 15 checkers on the board, none in your home. What’s it worth?',
          options: [
            { id: '1', text: '1 point', explanation: 'They bore off nothing, so this is a gammon: 2 points.' },
            { id: '2', text: '2 points', correct: true, explanation: 'A gammon: nothing borne off, but nothing left in your home board.' },
            { id: '3', text: '3 points', explanation: 'A backgammon also needs a checker in your home board or on the bar.' },
          ],
        },
      ],
    },
  ],
};
